server:
  port: 8080

spring:
    datasource:
        name: pubhub
        url: jdbc:mysql://www.firework.vip:3306/pubhub
        username: root
        password: syj123A!
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    redis:
      password: syj123
      hostName: 116.196.113.246
      port: 6379
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
      timeout: 0
    profiles:
      active: dev

management:
  security:
    #是否启用安全
    enabled: false
endpoints:
  autoconfig:
    enabled: true
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: vip.firework.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


